name: Make new release
on:
  push:
    paths:
      - 'released-versions/*'
jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git
        run: |
          git config --global pull.rebase true
          git config --global user.name "XYZ"
          git config --global user.email "ghost@example.com"
      - uses: actions/checkout@v3
        with:
          repository: jakub-k-slys/BetterGhost
          token: ${{ secrets.REPO_SCOPED_TOKEN }}
          path: 'BetterGhost'
      - name: Setup release version
        run: |
          echo "LATEST_VERSION=$(cat ./BetterGhost/released-versions/latest.txt)" >> $GITHUB_ENV
      - uses: actions/checkout@v3
        with:
          repository: TryGhost/Ghost
          token: ${{ secrets.REPO_SCOPED_TOKEN }}
          ref: ${{ env.LATEST_VERSION }}
      - uses: actions/checkout@v3
        with:
          repository: jakub-k-slys/BetterGhost
          token: ${{ secrets.REPO_SCOPED_TOKEN }}
          path: 'BetterGhost'
      - name: Patch vanilla release
        run: |
          patch -p0 < BetterGhost/configurable-batch-size.diff
      - name: Setup Node
        uses: actions/setup-node@v3
        env:
          FORCE_COLOR: 0
        with:
          node-version: '18.12.1'
          cache: yarn
      - name: Run yarn 
        run: yarn
      - name: Run yarn main:submodules
        run: yarn main:submodules
      - name: Create tarball
        run: npm pack
        working-directory: ghost/core
      - name: Publish new release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.LATEST_VERSION }}
          name: ${{ env.LATEST_VERSION }}
          token: ${{ secrets.REPO_SCOPED_TOKEN }}
          files: |
            ghost/core/ghost-*.tgz
