name: Make new release
on:
  push:
    paths:
      - 'released-versions/*'
jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: TryGhost/Ghost
          token: ${{ secrets.REPO_SCOPED_TOKEN }}
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.REPO_SCOPED_TOKEN }}
          path: './BetterGhost'
      - name: Setup release version
        run: |
          echo "LATEST_VERSION=$(cat BetterGhost/released-versions/latest.txt)" >> $GITHUB_ENV
      - name: Fetch latest released version
        run: |
          wget https://api.github.com/repos/TryGhost/Ghost/tarball/${{ env.LATEST_VERSION }} -O ghost.tar.gz
      - name: Unpack vanilla release
        run: |
          tar -xvzf ghost.tar.gz
      - name: Patch vanilla release
        run: |
          cd TryGhost-Ghost-*
          patch -p0 < ../configurable-batch-size.diff
      - name: Setup Node
        uses: actions/setup-node@v3
        env:
          FORCE_COLOR: 0
        with:
          node-version: '18.12.1'
          cache: yarn
          cache-dependency-path: ./TryGhost-Ghost-*/yarn.lock
      - name: Run yarn 
        run: | 
          cd TryGhost-Ghost-*
          yarn
      - name: Run yarn main:submodules
        run: |
          cd TryGhost-Ghost-*
          yarn main:submodules
      - name: Apply patch
        run: |
          cd TryGhost-Ghost-*
          patch -p0 < ../configurable-batch-size.diff
      - name: Create tarball
        run: |
          cd TryGhost-Ghost-*/ghost/core
          npm pack
#      - name: Archive patched version
#        run: |
#          tar -cvzf better-ghost-${{ env.LATEST_VERSION }}.tar.gz TryGhost-Ghost-*
      - name: Publish new release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.LATEST_VERSION }}
          name: ${{ env.LATEST_VERSION }}
          token: ${{ secrets.REPO_SCOPED_TOKEN }}
          files: |
            TryGhost-Ghost-*/ghost/core/ghost-*.tar.gz
