name: Make new release
on:
  push:
    paths:
      - 'released-versions/*'
env:
  LATEST_VERSION: ''
jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.REPO_SCOPED_TOKEN }}
      - name: Setup release version
        run: |
          LATEST_VERSION = $(cat released-versions/latest.txt)
          echo $LATEST_VERSION
      - name: Fetch latest released version
        run: |
          wget https://api.github.com/repos/TryGhost/Ghost/tarball/$LATEST_VERSION -o ghost.tar.gz
