name: Make new release
on:
  push:
    paths:
      - 'released-versions/*'
jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.REPO_SCOPED_TOKEN }}
      - name: Setup release version
        run: |
          echo "LATEST_VERSION=$(cat released-versions/latest.txt)" >> $GITHUB_ENV
          echo $LATEST_VERSION
      - name: Fetch latest released version
        run: |
          wget https://api.github.com/repos/TryGhost/Ghost/tarball/${{ env.LATEST_VERSION }} -o ghost.tar.gz
          mv ghost.tar.gz better-ghost-${{ env.LATEST_VERSION }}.tar.gz
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ env.LATEST_VERSION }}
          prerelease: false
          title: "Release better-ghost-${{ env.LATEST_VERSION }}.tar.gz"
          files: |
            better-ghost-${{ env.LATEST_VERSION }}.tar.gz
