name: Make new release
on:
  push:
    paths:
      - 'released-versions/*'
env:
  LATEST_VERSION: ''
jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.REPO_SCOPED_TOKEN }}
      - name: Setup release version
        run: |
          echo "LATEST_VERSION=$(cat released-versions/latest.txt)" >> $GITHUB_ENV
          echo $LATEST_VERSION
      - name: Fetch latest released version
        run: |
          wget https://api.github.com/repos/TryGhost/Ghost/tarball/${{ env.LATEST_VERSION }} -o ghost.tar.gz
          mv ghost.tar.gz better-ghost-${{ env.LATEST_VERSION }}.tar.gz
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ env.LATEST_VERSION }}
          release_name: Release ${{ env.LATEST_VERSION }}
          body: |
            Changes in this Release
            - tbd
          draft: false
          prerelease: false        
          artifacts: 'better-ghost-${{ env.LATEST_VERSION }}.tar.gz'
