name: Deploy Images to GHCR
on:
  release:
    types: [published]
  workflow_dispatch:
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Set up Git
        run: |
          git config --global pull.rebase true
          git config --global user.name "XYZ"
          git config --global user.email "ghost@example.com"
      - uses: actions/checkout@v3
        with:
          repository: jakub-k-slys/BetterGhost
          token: ${{ secrets.REPO_SCOPED_TOKEN }}
      - name: Setup release version
        run: |
          echo "LATEST_VERSION=$(cat ./released-versions/latest.txt)" >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.REPO_SCOPED_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.LATEST_VERSION }}, ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          labels: ${{ steps.meta.outputs.labels }}
          build-args: GHOST_VERSION=${{ env.LATEST_VERSION }}
